name: Build Go Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Make All
        run: |
          go build -o myapp
          mkdir -p dist
          mv myapp dist/

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: myapp
          path: dist/myapp
