name: Build and Upload Artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Go project
        run: |
          go build -o myapp
          mkdir -p dist
          mv myapp dist/

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: myapp
          path: dist/myapp
