name: goreleaser

on:
   workflow_dispatch:

jobs:
   goreleaser:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
         with:
           fetch-depth: 0

       - name: Set up Go
         uses: actions/setup-go@v5
         with:
           go-version: '1.22'
          
       - name: Make All
         run: |
           ./package.sh
       - name: Upload GoReleaser artifacts
         uses: actions/upload-artifact@v3
         with:
           name: my-artifacts
           path: |
             /home/runner/work/frp/frp/release/packages/*
